### ISSUE TITLE
Unsupported block type for private key: 82

### ISSUE THREAD

**Issue by cjamcu** [konstantinullrich/crypton#15]
```Unhandled exception:
Invalid argument(s): Unsupported block type for private key: 82
#0      PKCS1Encoding._decodeBlock (package:pointycastle/asymmetric/pkcs1.dart:142:7)
#1      PKCS1Encoding.processBlock (package:pointycastle/asymmetric/pkcs1.dart:94:14)
#2      RSAPrivateKey._processInBlocks (package:crypton/src/rsa/private_key.dart:101:30)
#3      RSAPrivateKey.decryptData (package:crypton/src/rsa/private_key.dart:84:12)
#4      RSAPrivateKey.decrypt (package:crypton/src/rsa/private_key.dart:77:19)
#5      main (package:premium/crypton.dart:27:30)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by konstantinullrich** [comment]
@cjamcu Can you please add some Code.

**Comment by maltub9** [comment]
I got the same error. after reading the encrypted string from a file.

**Comment by konstantinullrich** [comment]
@maltub9 Can you please share the code that failed
